[package]
name = "catr"
version = "0.1.0"
edition = "2021"
authors = [ "Gringo <gringonivoli@gmail.com>" ]

[dependencies]
anyhow = "1"
clap = { version = "4.5.4", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
pretty_assertions = "1.4.0"
rand = "0.8"
